<?php

namespace Database\Seeders;

use App\Models\Vehicule;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehiculeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Vehicule::create([
            'titre'                 => 'Audi_A1_1.6_TDI',
            'prix'                  => 15900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Audi A1 Sportback de 2018, très bien entretenue, avec seulement 25_000 km au compteur. Ce modèle offre une expérience de conduite agile et dynamique, alliant confort et style. Son moteur essence de 116 ch garantit des performances exceptionnelles. L'intérieur est spacieux et moderne, idéal pour vos trajets quotidiens ou vos escapades le week-end. Contrôle technique valide jusqu'au 20_05_2025.",
            'departement'           => 'Paris',
            'code_postal'           => '75001',
            'ville'                 => 'Paris',
            'cv_fiscaux'            => 4,
            'ch_din'                => 90,
            'kilometrage'           => 25000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-05-20',
            'premiere_main'         => true,
            'controle_technique'    => '2025-05-20',
            'energie'               => 'Essence',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 1,
            'couleur_id'            => 1,
            'marque_id'             => 6,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Renault_Clio_IV_1.5_DCI',
            'prix'                  => 10900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Renault Clio IV de 2017, en excellent état, avec seulement 35_000 km. Ce modèle est idéal pour la ville avec sa compacité et son faible coût d'entretien. Moteur diesel de 90 ch, boîte manuelle, et consommation économique. Intérieur confortable et bien équipé. Contrôle technique valide jusqu'au 15_07_2025.",
            'departement'           => 'Lyon',
            'code_postal'           => '69001',
            'ville'                 => 'Lyon',
            'cv_fiscaux'            => 4,
            'ch_din'                => 90,
            'kilometrage'           => 35000,
            'annee'                 => 2017,
            'statut'                => true,
            'Mise_en_circulation'   => '2017-06-01',
            'premiere_main'         => true,
            'controle_technique'    => '2025-07-15',
            'energie'               => 'Diesel',
            'type'                  => 'Coupé',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 2,
            'couleur_id'            => 2,
            'marque_id'             => 56,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Peugeot_208_1.2_PureTech',
            'prix'                  => 13900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Peugeot 208 de 2019, très bien entretenue, avec 20_000 km. Cette citadine est parfaite pour naviguer en ville grâce à sa taille Coupé. Moteur essence de 110 ch, économique et fiable. Aucune réparation à prévoir, voiture prête à prendre la route. Contrôle technique valide jusqu'au 30_08_2025.",
            'departement'           => 'Toulouse',
            'code_postal'           => '31000',
            'ville'                 => 'Toulouse',
            'cv_fiscaux'            => 5,
            'ch_din'                => 110,
            'kilometrage'           => 20000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-01-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-08-30',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 4,
            'couleur_id'            => 2,
            'marque_id'             => 51,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'BMW_Série_3_320d',
            'prix'                  => 24900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : BMW Série 3 de 2017, avec 40_000 km au compteur. Cette berline de luxe offre une expérience de conduite inégalée avec son moteur diesel de 190 ch. Bien équipée, avec un intérieur haut de gamme et un confort de conduite exceptionnel. Contrôle technique valide jusqu'au 25_12_2025.",
            'departement'           => 'Bordeaux',
            'code_postal'           => '33000',
            'ville'                 => 'Bordeaux',
            'cv_fiscaux'            => 6,
            'ch_din'                => 190,
            'kilometrage'           => 40000,
            'annee'                 => 2017,
            'statut'                => true,
            'Mise_en_circulation'   => '2017-07-10',
            'premiere_main'         => false,
            'controle_technique'    => '2025-12-25',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 5,
            'couleur_id'            => 2,
            'marque_id'             => 7,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Ford_Fiesta_1.0_EcoBoost',
            'prix'                  => 11900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Ford Fiesta de 2018, avec seulement 28_000 km. Ce modèle est parfait pour la conduite en ville avec son moteur essence de 100 ch, alliant performance et économie de carburant. Très bonne maniabilité et équipement complet. Contrôle technique valide jusqu'au 18_06_2025.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 28000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-04-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-06-18',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 6,
            'couleur_id'            => 2,
            'marque_id'             => 24,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Nissan_Qashqai_1.5_dCi',
            'prix'                  => 18900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Nissan Qashqai de 2019, avec 15_000 km. Ce 4x4_Suv_Crossover est idéal pour les familles, offrant confort et espace. Moteur diesel de 115 ch, faible consommation et équipements modernes. Aucun frais à prévoir, prêt à partir. Contrôle technique valide jusqu'au 22_05_2025.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 5,
            'ch_din'                => 115,
            'kilometrage'           => 15000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-06-30',
            'premiere_main'         => true,
            'controle_technique'    => '2025-05-22',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 7,
            'couleur_id'            => 2,
            'marque_id'             => 48,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Kia_Picanto_1.2',
            'prix'                  => 10900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Kia Picanto de 2020, avec 10_000 km. Une citadine Coupé et agile, idéale pour la ville. Moteur essence de 84 ch, faible consommation et entretien réduit. Première main, voiture très bien entretenue. Contrôle technique valide jusqu'au 05_09_2025.",
            'departement'           => 'Nantes',
            'code_postal'           => '44000',
            'ville'                 => 'Nantes',
            'cv_fiscaux'            => 4,
            'ch_din'                => 84,
            'kilometrage'           => 10000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-01-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-09-05',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 8,
            'couleur_id'            => 2,
            'marque_id'             => 34,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Mercedes_A_180d',
            'prix'                  => 22900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Mercedes-Benz Classe A de 2018, avec 30_000 km. Ce modèle allie luxe et performance avec son moteur diesel de 116 ch. Intérieur haut de gamme, équipements modernes, et conduite agréable. Contrôle technique valide jusqu'au 11_12_2025.",
            'departement'           => 'Lille',
            'code_postal'           => '59000',
            'ville'                 => 'Lille',
            'cv_fiscaux'            => 5,
            'ch_din'                => 116,
            'kilometrage'           => 30000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-09-05',
            'premiere_main'         => false,
            'controle_technique'    => '2025-12-11',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 9,
            'couleur_id'            => 2,
            'marque_id'             => 44,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Fiat_500_1.2',
            'prix'                  => 8500.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Fiat 500 de 2016, avec 40_000 km. Ce modèle emblématique est parfait pour la ville grâce à sa petite taille. Moteur essence de 69 ch, faible consommation et style unique. Première main, bien entretenue. Contrôle technique valide jusqu'au 15_01_2025.",
            'departement'           => 'Rennes',
            'code_postal'           => '35000',
            'ville'                 => 'Rennes',
            'cv_fiscaux'            => 4,
            'ch_din'                => 69,
            'kilometrage'           => 40000,
            'annee'                 => 2016,
            'statut'                => true,
            'Mise_en_circulation'   => '2016-03-20',
            'premiere_main'         => true,
            'controle_technique'    => '2025-01-15',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '4_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 10,
            'couleur_id'            => 2,
            'marque_id'             => 23,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Toyota_Yaris_1.5_Hybrid',
            'prix'                  => 15900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Toyota Yaris Hybrides de 2021, avec 5_000 km. Une petite voiture polyvalente et économique. Moteur Hybrides combinant performance et faibles émissions. Idéale pour la ville. Contrôle technique valide jusqu'au 30_07_2025.",
            'departement'           => 'Toulouse',
            'code_postal'           => '31000',
            'ville'                 => 'Toulouse',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 5000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-05-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-07-30',
            'energie'               => 'Hybrides',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 11,
            'couleur_id'            => 2,
            'marque_id'             => 66,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Peugeot_208_1.2_PureTech',
            'prix'                  => 13900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Peugeot 208 de 2020, avec 20_000 km. Une citadine au design moderne et sportif, équipée d'un moteur essence de 110 ch. Idéale pour la ville et les trajets quotidiens. Équipements complets. Contrôle technique valide jusqu'au 10_10_2025.",
            'departement'           => 'Lyon',
            'code_postal'           => '69000',
            'ville'                 => 'Lyon',
            'cv_fiscaux'            => 5,
            'ch_din'                => 110,
            'kilometrage'           => 20000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-06-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-10-10',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 12,
            'couleur_id'            => 2,
            'marque_id'             => 51,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Skoda_Octavia_2.0_TDI',
            'prix'                  => 19900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Skoda Octavia de 2018, avec 25_000 km. Une berline spacieuse avec un moteur diesel de 150 ch, offrant confort et efficacité. Idéale pour les longs trajets. Aucun frais à prévoir. Contrôle technique valide jusqu'au 15_11_2025.",
            'departement'           => 'Bordeaux',
            'code_postal'           => '33000',
            'ville'                 => 'Bordeaux',
            'cv_fiscaux'            => 6,
            'ch_din'                => 150,
            'kilometrage'           => 25000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-04-10',
            'premiere_main'         => false,
            'controle_technique'    => '2025-11-15',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 13,
            'couleur_id'            => 2,
            'marque_id'             => 13,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Volkswagen_Golf_1.6_TDI',
            'prix'                  => 21900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Volkswagen Golf de 2019, avec 18_000 km. Une Coupé polyvalente avec un moteur diesel de 115 ch, idéale pour tous vos trajets. Très bien équipée et confortable. Contrôle technique valide jusqu'au 20_04_2025.",
            'departement'           => 'Marseille',
            'code_postal'           => '13000',
            'ville'                 => 'Marseille',
            'cv_fiscaux'            => 5,
            'ch_din'                => 115,
            'kilometrage'           => 18000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-09-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-04-20',
            'energie'               => 'Diesel',
            'type'                  => 'Coupé',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 14,
            'couleur_id'            => 2,
            'marque_id'             => 14,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Renault_Captur_1.5_dCi',
            'prix'                  => 17900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Renault Captur de 2020, avec 12_000 km. Un 4x4_Suv_Crossover compact avec un moteur diesel de 95 ch, alliant confort et modularité. Idéal pour les sorties en famille. Contrôle technique valide jusqu'au 30_05_2025.",
            'departement'           => 'Lille',
            'code_postal'           => '59000',
            'ville'                 => 'Lille',
            'cv_fiscaux'            => 5,
            'ch_din'                => 95,
            'kilometrage'           => 12000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-08-20',
            'premiere_main'         => true,
            'controle_technique'    => '2025-05-30',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 15,
            'couleur_id'            => 2,
            'marque_id'             => 56,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Hyundai_Tucson_1.6_GDi',
            'prix'                  => 22900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Hyundai Tucson de 2019, avec 22_000 km. Un 4x4_Suv_Crossover spacieux et bien équipé, moteur essence de 132 ch. Confort optimal et faible consommation. Aucun frais à prévoir, voiture comme neuve. Contrôle technique valide jusqu'au 10_11_2025.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 6,
            'ch_din'                => 132,
            'kilometrage'           => 22000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-03-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-11-10',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 16,
            'couleur_id'            => 2,
            'marque_id'             => 16,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Citroen_C3_1.2_PureTech',
            'prix'                  => 12900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Citroën C3 de 2021, avec 10_000 km. Une citadine au style unique, équipée d'un moteur essence de 82 ch. Confort et praticité au rendez-vous. Contrôle technique valide jusqu'au 15_02_2025.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 4,
            'ch_din'                => 82,
            'kilometrage'           => 10000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-01-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-02-15',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 17,
            'couleur_id'            => 2,
            'marque_id'             => 17,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Nissan_Qashqai_1.5_dCi',
            'prix'                  => 19900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Nissan Qashqai de 2018, avec 30_000 km. Un 4x4_Suv_Crossover élégant et spacieux avec un moteur diesel de 110 ch. Parfait pour les familles et les trajets en ville. Équipements modernes et confort optimal. Contrôle technique valide jusqu'au 01_12_2025.",
            'departement'           => 'Toulouse',
            'code_postal'           => '31000',
            'ville'                 => 'Toulouse',
            'cv_fiscaux'            => 5,
            'ch_din'                => 110,
            'kilometrage'           => 30000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-05-25',
            'premiere_main'         => false,
            'controle_technique'    => '2025-12-01',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 18,
            'couleur_id'            => 2,
            'marque_id'             => 48,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Ford_Fiesta_1.0_EcoBoost',
            'prix'                  => 13900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Ford Fiesta de 2020, avec 15_000 km. Une citadine dynamique avec un moteur essence de 100 ch, alliant performance et économie de carburant. Idéale pour la ville. Contrôle technique valide jusqu'au 12_08_2025.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 15000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-04-01',
            'premiere_main'         => true,
            'controle_technique'    => '2025-08-12',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 19,
            'couleur_id'            => 2,
            'marque_id'             => 24,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Kia_Sportage_1.7_CRDi',
            'prix'                  => 23900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Kia Sportage de 2019, avec 28_000 km. Un 4x4_Suv_Crossover robuste et spacieux avec un moteur diesel de 141 ch, parfait pour les familles et les aventures. Très bien équipé. Contrôle technique valide jusqu'au 10_09_2025.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 7,
            'ch_din'                => 141,
            'kilometrage'           => 28000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-03-30',
            'premiere_main'         => true,
            'controle_technique'    => '2025-09-10',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 20,
            'couleur_id'            => 2,
            'marque_id'             => 34,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'BMW_Série_3_2.0_d',
            'prix'                  => 29900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : BMW Série 3 de 2017, avec 35_000 km. Une berline premium avec un moteur diesel de 150 ch, alliant confort et sportivité. Idéale pour les trajets longs et les professionnels. Contrôle technique valide jusqu'au 15_03_2025.",
            'departement'           => 'Paris',
            'code_postal'           => '75000',
            'ville'                 => 'Paris',
            'cv_fiscaux'            => 7,
            'ch_din'                => 150,
            'kilometrage'           => 35000,
            'annee'                 => 2017,
            'statut'                => true,
            'Mise_en_circulation'   => '2017-06-15',
            'premiere_main'         => false,
            'controle_technique'    => '2025-03-15',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 21,
            'couleur_id'            => 2,
            'marque_id'             => 7,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Mercedes-Benz_Classe_A_180_d',
            'prix'                  => 24900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Mercedes-Benz Classe A de 2018, avec 25_000 km. Une Coupé luxueuse avec un moteur diesel de 116 ch, offrant un confort de conduite exceptionnel. Équipements haut de gamme. Contrôle technique valide jusqu'au 20_10_2025.",
            'departement'           => 'Lille',
            'code_postal'           => '59000',
            'ville'                 => 'Lille',
            'cv_fiscaux'            => 6,
            'ch_din'                => 116,
            'kilometrage'           => 25000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-05-05',
            'premiere_main'         => true,
            'controle_technique'    => '2025-10-20',
            'energie'               => 'Diesel',
            'type'                  => 'Coupé',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 22,
            'couleur_id'            => 2,
            'marque_id'             => 44,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Fiat_500_1.2_Essence',
            'prix'                  => 10900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Fiat 500 de 2020, avec 12_000 km. Une citadine au look rétro avec un moteur essence de 69 ch. Parfaite pour la ville, style et économie de carburant. Contrôle technique valide jusqu'au 01_11_2025.",
            'departement'           => 'Bordeaux',
            'code_postal'           => '33000',
            'ville'                 => 'Bordeaux',
            'cv_fiscaux'            => 4,
            'ch_din'                => 69,
            'kilometrage'           => 12000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-02-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-11-01',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '4_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 23,
            'couleur_id'            => 2,
            'marque_id'             => 23,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Peugeot_208_1.2_Essence',
            'prix'                  => 12900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Peugeot 208 de 2021, avec 8_000 km. Une citadine dynamique avec un moteur essence de 100 ch. Parfaite pour les trajets urbains, alliant style et performance. Contrôle technique valide jusqu'au 15_05_2026.",
            'departement'           => 'Marseille',
            'code_postal'           => '13000',
            'ville'                 => 'Marseille',
            'cv_fiscaux'            => 5,
            'ch_din'                => 100,
            'kilometrage'           => 8000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-03-10',
            'premiere_main'         => true,
            'controle_technique'    => '2026-05-15',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Non_Roulante_Réparation_Obligatoire',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 24,
            'couleur_id'            => 2,
            'marque_id'             => 51,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Audi_A4_2.0_TDI',
            'prix'                  => 32900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Audi A4 de 2018, avec 40_000 km. Une berline haut de gamme avec un moteur diesel de 150 ch. Alliant confort et performance sur la route. Contrôle technique valide jusqu'au 05_11_2025.",
            'departement'           => 'Lyon',
            'code_postal'           => '69000',
            'ville'                 => 'Lyon',
            'cv_fiscaux'            => 7,
            'ch_din'                => 150,
            'kilometrage'           => 40000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-02-20',
            'premiere_main'         => false,
            'controle_technique'    => '2025-11-05',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 25,
            'couleur_id'            => 2,
            'marque_id'             => 6,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Renault_Clio_1.5_dCi',
            'prix'                  => 15900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Renault Clio de 2019, avec 25_000 km. Une citadine polyvalente avec un moteur diesel de 85 ch. Économique et idéale pour les trajets quotidiens. Contrôle technique valide jusqu'au 15_06_2025.",
            'departement'           => 'Nantes',
            'code_postal'           => '44000',
            'ville'                 => 'Nantes',
            'cv_fiscaux'            => 4,
            'ch_din'                => 85,
            'kilometrage'           => 25000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-04-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-06-15',
            'energie'               => 'Diesel',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 26,
            'couleur_id'            => 2,
            'marque_id'             => 56,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Toyota_Yaris_1.5_Hybrid',
            'prix'                  => 18900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Toyota Yaris de 2020, avec 10_000 km. Une citadine Hybrides, économe en carburant avec un moteur de 100 ch. Idéale pour la ville, alliant confort et technologie. Contrôle technique valide jusqu'au 22_04_2026.",
            'departement'           => 'Toulon',
            'code_postal'           => '83000',
            'ville'                 => 'Toulon',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 10000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-01-15',
            'premiere_main'         => true,
            'controle_technique'    => '2026-04-22',
            'energie'               => 'Hybrides',
            'type'                  => 'Citadine',
            'etat'                  => 'Non_Roulante_Réparation_Obligatoire',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 27,
            'couleur_id'            => 2,
            'marque_id'             => 66,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Skoda_Octavia_1.6_TDI',
            'prix'                  => 21900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Skoda Octavia de 2018, avec 33_000 km. Une berline spacieuse avec un moteur diesel de 115 ch. Pratique pour les familles et les professionnels. Contrôle technique valide jusqu'au 20_05_2025.",
            'departement'           => 'Brest',
            'code_postal'           => '29200',
            'ville'                 => 'Brest',
            'cv_fiscaux'            => 6,
            'ch_din'                => 115,
            'kilometrage'           => 33000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-09-10',
            'premiere_main'         => false,
            'controle_technique'    => '2025-05-20',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 28,
            'couleur_id'            => 2,
            'marque_id'             => 28,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Honda_Civic_1.0_Turbo',
            'prix'                  => 22900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Honda Civic de 2021, avec 5_000 km. Une berline sportive avec un moteur essence turbo de 126 ch. Style audacieux et conduite agréable. Contrôle technique valide jusqu'au 10_12_2026.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 6,
            'ch_din'                => 126,
            'kilometrage'           => 5000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-06-15',
            'premiere_main'         => true,
            'controle_technique'    => '2026-12-10',
            'energie'               => 'Essence',
            'type'                  => 'Berline',
            'etat'                  => 'Non_Roulante_Réparation_Obligatoire',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 29,
            'couleur_id'            => 2,
            'marque_id'             => 29,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Nissan_Qashqai_1.3_Essence',
            'prix'                  => 23900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Nissan Qashqai de 2020, avec 15_000 km. Un 4x4_Suv_Crossover compact avec un moteur essence de 140 ch. Idéal pour la ville et les escapades. Contrôle technique valide jusqu'au 30_08_2026.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 7,
            'ch_din'                => 140,
            'kilometrage'           => 15000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-05-20',
            'premiere_main'         => true,
            'controle_technique'    => '2026-08-30',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Non_Roulante_Réparation_Obligatoire',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 30,
            'couleur_id'            => 2,
            'marque_id'             => 48,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'BMW_Série_3_320d',
            'prix'                  => 34900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : BMW Série 3 de 2019, avec 22_000 km. Une berline de luxe avec un moteur diesel de 190 ch. Performances sportives et confort inégalé. Contrôle technique valide jusqu'au 15_11_2025.",
            'departement'           => 'Bordeaux',
            'code_postal'           => '33000',
            'ville'                 => 'Bordeaux',
            'cv_fiscaux'            => 8,
            'ch_din'                => 190,
            'kilometrage'           => 22000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-01-30',
            'premiere_main'         => false,
            'controle_technique'    => '2025-11-15',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 31,
            'couleur_id'            => 2,
            'marque_id'             => 7,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Kia_Sportage_1.6_GDI',
            'prix'                  => 22900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Kia Sportage de 2021, avec 8_500 km. Un 4x4_Suv_Crossover spacieux et confortable avec un moteur essence de 132 ch. Parfait pour toute la famille. Contrôle technique valide jusqu'au 18_07_2026.",
            'departement'           => 'Toulouse',
            'code_postal'           => '31000',
            'ville'                 => 'Toulouse',
            'cv_fiscaux'            => 6,
            'ch_din'                => 132,
            'kilometrage'           => 8500,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-03-25',
            'premiere_main'         => true,
            'controle_technique'    => '2026-07-18',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Non_Roulante_Réparation_Obligatoire',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 32,
            'couleur_id'            => 2,
            'marque_id'             => 34,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Seat_Leon_1.5_EcoTSI',
            'prix'                  => 19900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Seat Leon de 2020, avec 12_000 km. Une berline dynamique avec un moteur essence de 150 ch. Design moderne et agrément de conduite exceptionnel. Contrôle technique valide jusqu'au 28_02_2026.",
            'departement'           => 'Lille',
            'code_postal'           => '59000',
            'ville'                 => 'Lille',
            'cv_fiscaux'            => 6,
            'ch_din'                => 150,
            'kilometrage'           => 12000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-04-10',
            'premiere_main'         => true,
            'controle_technique'    => '2026-02-28',
            'energie'               => 'Essence',
            'type'                  => 'Berline',
            'etat'                  => 'Roulante_Réparations_Nécessaires',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 33,
            'couleur_id'            => 2,
            'marque_id'             => 33,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Ford_Fiesta_1.0_EcoBoost',
            'prix'                  => 15900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Ford Fiesta de 2019, avec 30_000 km. Une citadine agile avec un moteur essence turbo de 100 ch. Idéale pour la ville. Contrôle technique valide jusqu'au 11_05_2025.",
            'departement'           => 'Grenoble',
            'code_postal'           => '38000',
            'ville'                 => 'Grenoble',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 30000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-08-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-05-11',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 34,
            'couleur_id'            => 2,
            'marque_id'             => 24,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Peugeot_3008_1.5_BlueHDi',
            'prix'                  => 27900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Peugeot 3008 de 2020, avec 20_000 km. Un 4x4_Suv_Crossover élégant avec un moteur diesel de 130 ch. Confort et espace intérieur exceptionnel. Contrôle technique valide jusqu'au 22_06_2026.",
            'departement'           => 'Marseille',
            'code_postal'           => '13000',
            'ville'                 => 'Marseille',
            'cv_fiscaux'            => 7,
            'ch_din'                => 130,
            'kilometrage'           => 20000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-09-15',
            'premiere_main'         => true,
            'controle_technique'    => '2026-06-22',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Roulante_Réparations_Nécessaires',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 35,
            'couleur_id'            => 2,
            'marque_id'             => 51,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Audi_A3_1.5_TFSI',
            'prix'                  => 29900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Audi A3 de 2018, avec 25_000 km. Une berline Coupé avec un moteur essence de 150 ch. Design sophistiqué et technologie avancée. Contrôle technique valide jusqu'au 12_11_2025.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 7,
            'ch_din'                => 150,
            'kilometrage'           => 25000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-03-05',
            'premiere_main'         => false,
            'controle_technique'    => '2025-11-12',
            'energie'               => 'Essence',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 36,
            'couleur_id'            => 2,
            'marque_id'             => 6,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Mercedes_Classe_A_A180',
            'prix'                  => 32900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Mercedes-Benz Classe A de 2019, avec 18_000 km. Une Coupé premium avec un moteur diesel de 116 ch. Confort et technologies de pointe. Contrôle technique valide jusqu'au 15_04_2025.",
            'departement'           => 'Nantes',
            'code_postal'           => '44000',
            'ville'                 => 'Nantes',
            'cv_fiscaux'            => 5,
            'ch_din'                => 116,
            'kilometrage'           => 18000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-06-10',
            'premiere_main'         => true,
            'controle_technique'    => '2025-04-15',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 37,
            'couleur_id'            => 2,
            'marque_id'             => 44,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Honda_CR-V_2.0i',
            'prix'                  => 28900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Honda CR-V de 2020, avec 12_500 km. Un 4x4_Suv_Crossover spacieux avec un moteur essence de 150 ch. Fiabilité et confort. Contrôle technique valide jusqu'au 22_07_2026.",
            'departement'           => 'Lyon',
            'code_postal'           => '69000',
            'ville'                 => 'Lyon',
            'cv_fiscaux'            => 7,
            'ch_din'                => 150,
            'kilometrage'           => 12500,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-08-18',
            'premiere_main'         => true,
            'controle_technique'    => '2026-07-22',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 38,
            'couleur_id'            => 2,
            'marque_id'             => 38,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Skoda_Octavia_1.6_TDI',
            'prix'                  => 21900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Skoda Octavia de 2018, avec 30_000 km. Une berline spacieuse avec un moteur diesel de 115 ch. Parfaite pour les familles. Contrôle technique valide jusqu'au 30_03_2026.",
            'departement'           => 'Rennes',
            'code_postal'           => '35000',
            'ville'                 => 'Rennes',
            'cv_fiscaux'            => 6,
            'ch_din'                => 115,
            'kilometrage'           => 30000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-10-15',
            'premiere_main'         => false,
            'controle_technique'    => '2026-03-30',
            'energie'               => 'Diesel',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 39,
            'couleur_id'            => 2,
            'marque_id'             => 39,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Toyota_C-HR_1.8_Hybrid',
            'prix'                  => 24900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Toyota C-HR de 2021, avec 10_000 km. Un 4x4_Suv_Crossover Hybrides avec un moteur de 122 ch. Économie de carburant et style moderne. Contrôle technique valide jusqu'au 15_09_2026.",
            'departement'           => 'Marseille',
            'code_postal'           => '13000',
            'ville'                 => 'Marseille',
            'cv_fiscaux'            => 6,
            'ch_din'                => 122,
            'kilometrage'           => 10000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-05-20',
            'premiere_main'         => true,
            'controle_technique'    => '2026-09-15',
            'energie'               => 'Hybrides',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 40,
            'couleur_id'            => 2,
            'marque_id'             => 66,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Renault_Captur_1.3_TCe',
            'prix'                  => 20900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Renault Captur de 2020, avec 15_000 km. Un 4x4_Suv_Crossover urbain avec un moteur essence de 130 ch. Idéal pour la ville. Contrôle technique valide jusqu'au 20_10_2025.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 6,
            'ch_din'                => 130,
            'kilometrage'           => 15000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-09-10',
            'premiere_main'         => true,
            'controle_technique'    => '2025-10-20',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 41,
            'couleur_id'            => 2,
            'marque_id'             => 56,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Ford_Fiesta_1.0_EcoBoost',
            'prix'                  => 13900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Ford Fiesta de 2019, avec 20_000 km. Une citadine dynamique avec un moteur essence de 100 ch. Économique et agréable à conduire. Contrôle technique valide jusqu'au 10_01_2025.",
            'departement'           => 'Toulouse',
            'code_postal'           => '31000',
            'ville'                 => 'Toulouse',
            'cv_fiscaux'            => 4,
            'ch_din'                => 100,
            'kilometrage'           => 20000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-04-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-01-10',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 42,
            'couleur_id'            => 2,
            'marque_id'             => 24,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Nissan_Qashqai_1.5_dCi',
            'prix'                  => 23900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Nissan Qashqai de 2018, avec 28_000 km. Un 4x4_Suv_Crossover polyvalent avec un moteur diesel de 115 ch. Confort et espace pour la famille. Contrôle technique valide jusqu'au 12_06_2025.",
            'departement'           => 'Bordeaux',
            'code_postal'           => '33000',
            'ville'                 => 'Bordeaux',
            'cv_fiscaux'            => 6,
            'ch_din'                => 115,
            'kilometrage'           => 28000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-11-20',
            'premiere_main'         => true,
            'controle_technique'    => '2025-06-12',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 43,
            'couleur_id'            => 2,
            'marque_id'             => 48,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Citroen_C3_1.2_PureTech',
            'prix'                  => 12900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Citroën C3 de 2020, avec 15_000 km. Une citadine moderne avec un moteur essence de 110 ch. Confort et design unique. Contrôle technique valide jusqu'au 15_12_2025.",
            'departement'           => 'Strasbourg',
            'code_postal'           => '67000',
            'ville'                 => 'Strasbourg',
            'cv_fiscaux'            => 5,
            'ch_din'                => 110,
            'kilometrage'           => 15000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-06-30',
            'premiere_main'         => true,
            'controle_technique'    => '2025-12-15',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 44,
            'couleur_id'            => 2,
            'marque_id'             => 44,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Kia_Sportage_1.6_GDI',
            'prix'                  => 26900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Kia Sportage de 2019, avec 18_000 km. Un 4x4_Suv_Crossover spacieux et confortable avec un moteur essence de 132 ch. Idéal pour la famille. Contrôle technique valide jusqu'au 20_11_2025.",
            'departement'           => 'Lille',
            'code_postal'           => '59000',
            'ville'                 => 'Lille',
            'cv_fiscaux'            => 7,
            'ch_din'                => 132,
            'kilometrage'           => 18000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-09-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-11-20',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 45,
            'couleur_id'            => 2,
            'marque_id'             => 34,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Peugeot_3008_1.5_BlueHDi',
            'prix'                  => 28900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Peugeot 3008 de 2020, avec 22_000 km. Un 4x4_Suv_Crossover au design moderne avec un moteur diesel de 130 ch. Confort et technologies embarquées. Contrôle technique valide jusqu'au 15_08_2025.",
            'departement'           => 'Grenoble',
            'code_postal'           => '38000',
            'ville'                 => 'Grenoble',
            'cv_fiscaux'            => 7,
            'ch_din'                => 130,
            'kilometrage'           => 22000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-03-05',
            'premiere_main'         => true,
            'controle_technique'    => '2025-08-15',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 46,
            'couleur_id'            => 2,
            'marque_id'             => 51,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);

        Vehicule::create([
            'titre'                 => 'Volkswagen_Golf_1.5_TSI',
            'prix'                  => 23900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Volkswagen Golf de 2020, avec 15_000 km. Une berline Coupé avec un moteur essence de 150 ch. Parfaite pour la ville et les longs trajets. Contrôle technique valide jusqu'au 10_11_2025.",
            'departement'           => 'Nantes',
            'code_postal'           => '44000',
            'ville'                 => 'Nantes',
            'cv_fiscaux'            => 7,
            'ch_din'                => 150,
            'kilometrage'           => 15000,
            'annee'                 => 2020,
            'statut'                => true,
            'Mise_en_circulation'   => '2020-01-12',
            'premiere_main'         => true,
            'controle_technique'    => '2025-11-10',
            'energie'               => 'Essence',
            'type'                  => 'Berline',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 47,
            'couleur_id'            => 2,
            'marque_id'             => 47,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Renault_Captur_1.3_TCe',
            'prix'                  => 19900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Renault Captur de 2021, avec 12_000 km. Un 4x4_Suv_Crossover élégant avec un moteur essence de 130 ch. Idéal pour la ville avec un grand confort. Contrôle technique valide jusqu'au 05_09_2025.",
            'departement'           => 'Marseille',
            'code_postal'           => '13000',
            'ville'                 => 'Marseille',
            'cv_fiscaux'            => 6,
            'ch_din'                => 130,
            'kilometrage'           => 12000,
            'annee'                 => 2021,
            'statut'                => true,
            'Mise_en_circulation'   => '2021-03-15',
            'premiere_main'         => true,
            'controle_technique'    => '2025-09-05',
            'energie'               => 'Essence',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Pour_Pièces',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 48,
            'couleur_id'            => 2,
            'marque_id'             => 56,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Fiat_500_1.2',
            'prix'                  => 10900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Fiat 500 de 2019, avec 25_000 km. Une citadine au style rétro avec un moteur essence de 69 ch. Parfaite pour la ville. Contrôle technique valide jusqu'au 01_10_2025.",
            'departement'           => 'Nice',
            'code_postal'           => '06000',
            'ville'                 => 'Nice',
            'cv_fiscaux'            => 4,
            'ch_din'                => 69,
            'kilometrage'           => 25000,
            'annee'                 => 2019,
            'statut'                => true,
            'Mise_en_circulation'   => '2019-05-10',
            'premiere_main'         => true,
            'controle_technique'    => '2025-10-01',
            'energie'               => 'Essence',
            'type'                  => 'Citadine',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '4_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_manuelle',
            'user_id'               => 49,
            'couleur_id'            => 2,
            'marque_id'             => 23,
            'euro_id'               => 1,
            'critair_id'            => 1,
        ]);

        Vehicule::create([
            'titre'                 => 'Volvo_XC60_2.0_D4',
            'prix'                  => 35900.00,
            'image'                 => 'defaultVehicule.jpg',
            'description'           => "À vendre : Volvo XC60 de 2018, avec 30_000 km. Un 4x4_Suv_Crossover premium avec un moteur diesel de 190 ch. Alliant confort et sécurité. Contrôle technique valide jusqu'au 15_12_2025.",
            'departement'           => 'Lyon',
            'code_postal'           => '69000',
            'ville'                 => 'Lyon',
            'cv_fiscaux'            => 8,
            'ch_din'                => 190,
            'kilometrage'           => 30000,
            'annee'                 => 2018,
            'statut'                => true,
            'Mise_en_circulation'   => '2018-06-01',
            'premiere_main'         => true,
            'controle_technique'    => '2025-12-15',
            'energie'               => 'Diesel',
            'type'                  => '4x4_Suv_Crossover',
            'etat'                  => 'Sans_frais_à_Prévoir',
            'place'                 => '5_places',
            'porte'                 => '4_portes',
            'transmission'          => 'Boîte_automatique',
            'user_id'               => 50,
            'couleur_id'            => 2,
            'marque_id'             => 50,
            'euro_id'               => 1,
            'critair_id'            => 2,
        ]);
    }
}
